application: prebacked-hrd
# Current version 5-28-2
version: dev2
runtime: python27
api_version: 1
threadsafe: true


builtins:
- appstats: on


handlers:

- url: /
  script: main.application

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /templatetags
  static_dir: templatetags

- url: /admin_add
  script: main.application
  login: admin

- url: /admin_add/.*
  script: main.application
  login: admin

- url: /admin_add/ignition
  script: main.application
  login: admin

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: templates/robots.txt
  upload: templates/robots.txt

- url: /sitemap.xml
  static_files: templates/sitemap.xml
  upload: templates/sitemap.xml

- url: /.*
  script: main.application